domain_path: C:\Users\danie\Vitis_Workspace\pmod_wrapper_dynclk\export\pmod_wrapper_dynclk\sw\standalone_microblaze_0
app_src_dir: D:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
