#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XGPIO_NUM_INSTANCES 3

/* Definitions for peripheral AXI_GPIO_BUTTON */
#define XPAR_AXI_GPIO_BUTTON_COMPATIBLE xlnx,axi-gpio-2.0
#define XPAR_AXI_GPIO_BUTTON_BASEADDR 0x40000000
#define XPAR_AXI_GPIO_BUTTON_HIGHADDR 0x4000ffff
#define XPAR_AXI_GPIO_BUTTON_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_BUTTON_IS_DUAL 0x0
#define XPAR_AXI_GPIO_BUTTON_GPIO_WIDTH 0x4

/* Canonical definitions for peripheral AXI_GPIO_BUTTON */
#define XPAR_XGPIO_0_BASEADDR 0x40000000
#define XPAR_XGPIO_0_HIGHADDR 0x4000ffff
#define XPAR_XGPIO_0_COMPATIBLE xlnx,axi-gpio-2.0
#define XPAR_XGPIO_0_GPIO_WIDTH 0x4
#define XPAR_XGPIO_0_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_0_IS_DUAL 0x0

/* Definitions for peripheral AXI_GPIO_LED */
#define XPAR_AXI_GPIO_LED_COMPATIBLE xlnx,axi-gpio-2.0
#define XPAR_AXI_GPIO_LED_BASEADDR 0x40010000
#define XPAR_AXI_GPIO_LED_HIGHADDR 0x4001ffff
#define XPAR_AXI_GPIO_LED_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_LED_IS_DUAL 0x0
#define XPAR_AXI_GPIO_LED_GPIO_WIDTH 0x4

/* Canonical definitions for peripheral AXI_GPIO_LED */
#define XPAR_XGPIO_1_BASEADDR 0x40010000
#define XPAR_XGPIO_1_HIGHADDR 0x4001ffff
#define XPAR_XGPIO_1_COMPATIBLE xlnx,axi-gpio-2.0
#define XPAR_XGPIO_1_GPIO_WIDTH 0x4
#define XPAR_XGPIO_1_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_1_IS_DUAL 0x0

/* Definitions for peripheral AXI_GPIO_RGB_LED */
#define XPAR_AXI_GPIO_RGB_LED_COMPATIBLE xlnx,axi-gpio-2.0
#define XPAR_AXI_GPIO_RGB_LED_BASEADDR 0x40020000
#define XPAR_AXI_GPIO_RGB_LED_HIGHADDR 0x4002ffff
#define XPAR_AXI_GPIO_RGB_LED_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_RGB_LED_IS_DUAL 0x0
#define XPAR_AXI_GPIO_RGB_LED_GPIO_WIDTH 0xc

/* Canonical definitions for peripheral AXI_GPIO_RGB_LED */
#define XPAR_XGPIO_2_BASEADDR 0x40020000
#define XPAR_XGPIO_2_HIGHADDR 0x4002ffff
#define XPAR_XGPIO_2_COMPATIBLE xlnx,axi-gpio-2.0
#define XPAR_XGPIO_2_GPIO_WIDTH 0xc
#define XPAR_XGPIO_2_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_2_IS_DUAL 0x0

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_MICROBLAZE_0_AXI_INTC_COMPATIBLE xlnx,axi-intc-4.1
#define XPAR_MICROBLAZE_0_AXI_INTC_BASEADDR 0x41200000
#define XPAR_MICROBLAZE_0_AXI_INTC_HIGHADDR 0x4120ffff
#define XPAR_MICROBLAZE_0_AXI_INTC_KIND_OF_INTR 0x3
#define XPAR_MICROBLAZE_0_AXI_INTC_IS_FAST 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_IVAR_RST_VAL 0x10
#define XPAR_MICROBLAZE_0_AXI_INTC_NUM_INTR_INPUTS 0x2
#define XPAR_MICROBLAZE_0_AXI_INTC_ADDR_WIDTH 0x20
#define XPAR_MICROBLAZE_0_AXI_INTC_OPTIONS 0x0
#define XPAR_MICROBLAZE_0_AXI_INTC_INTCTYPE 0x0
#define XPAR_MICROBLAZE_0_AXI_INTC_HANDLER_TABLE 0x0

/* Canonical definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_XINTC_0_BASEADDR 0x41200000
#define XPAR_XINTC_0_HIGHADDR 0x4120ffff
#define XPAR_XINTC_0_HANDLER_TABLE 0x0
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE xlnx,axi-intc-4.1
#define XPAR_XINTC_0_IS_FAST 0x1
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_INTCTYPE 0x0
#define XPAR_XINTC_0_KIND_OF_INTR 0x3
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x2
#define XPAR_XINTC_0_OPTIONS 0x0

#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral AXI_UARTLITE */
#define XPAR_AXI_UARTLITE_COMPATIBLE xlnx,axi-uartlite-2.0
#define XPAR_AXI_UARTLITE_BASEADDR 0x40600000
#define XPAR_AXI_UARTLITE_HIGHADDR 0x4060ffff
#define XPAR_AXI_UARTLITE_BAUDRATE 0x2580
#define XPAR_AXI_UARTLITE_USE_PARITY 0x0
#define XPAR_AXI_UARTLITE_ODD_PARITY 0x0
#define XPAR_AXI_UARTLITE_DATA_BITS 0x8

/* Canonical definitions for peripheral AXI_UARTLITE */
#define XPAR_XUARTLITE_0_BASEADDR 0x40600000
#define XPAR_XUARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_XUARTLITE_0_BAUDRATE 0x2580
#define XPAR_XUARTLITE_0_COMPATIBLE xlnx,axi-uartlite-2.0
#define XPAR_XUARTLITE_0_DATA_BITS 0x8
#define XPAR_XUARTLITE_0_ODD_PARITY 0x0
#define XPAR_XUARTLITE_0_USE_PARITY 0x0

/*  BOARD definition */
#define XPS_BOARD_ARTY-A7-100

#define XPAR_MIG_0_BASEADDRESS 0x80000000
#define XPAR_MIG_0_HIGHADDRESS 0x90000000
#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x2000
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100015812

#define XPAR_MICROBLAZE_ADDR_SIZE 32

#define STDOUT_BASEADDRESS 0x40600000
#define STDIN_BASEADDRESS 0x40600000

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "7a100t"

#endif  /* end of protection macro */