# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Users/Daniel/Documents/VivadoProjects/MyNewProject/MyNewProject.srcs/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_6/PmodIPs_axi_gpio_0_6.xci
# IP: The module: 'PmodIPs_axi_gpio_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Daniel/Documents/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_6/PmodIPs_axi_gpio_0_6_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Users/Daniel/Documents/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_6/PmodIPs_axi_gpio_0_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Users/Daniel/Documents/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_6/PmodIPs_axi_gpio_0_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Users/Daniel/Documents/VivadoProjects/MyNewProject/MyNewProject.srcs/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_6/PmodIPs_axi_gpio_0_6.xci
# IP: The module: 'PmodIPs_axi_gpio_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Daniel/Documents/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_6/PmodIPs_axi_gpio_0_6_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Users/Daniel/Documents/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_6/PmodIPs_axi_gpio_0_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Users/Daniel/Documents/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_6/PmodIPs_axi_gpio_0_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_axi_gpio_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
