# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/UOA/Y4S1/P4P/Project/project_new_start_try_DC/project_new_start_try_DC.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4.xci
# IP: The module: 'design_1_axi_gpio_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/UOA/Y4S1/P4P/Project/project_new_start_try_DC/project_new_start_try_DC.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/UOA/Y4S1/P4P/Project/project_new_start_try_DC/project_new_start_try_DC.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/UOA/Y4S1/P4P/Project/project_new_start_try_DC/project_new_start_try_DC.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/UOA/Y4S1/P4P/Project/project_new_start_try_DC/project_new_start_try_DC.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4.xci
# IP: The module: 'design_1_axi_gpio_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/UOA/Y4S1/P4P/Project/project_new_start_try_DC/project_new_start_try_DC.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/UOA/Y4S1/P4P/Project/project_new_start_try_DC/project_new_start_try_DC.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/UOA/Y4S1/P4P/Project/project_new_start_try_DC/project_new_start_try_DC.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
