# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.runs/synth_1/PmodIPs_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {D:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.cache/wt} [current_project]
set_property parent.project_path {D:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:arty-a7-100:part0:1.1 [current_project]
set_property ip_output_repo {d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {{D:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/hdl/PmodIPs_wrapper.v}}
add_files {{D:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.srcs/sources_1/bd/PmodIPs/PmodIPs.bd}}
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_microblaze_0_0/PmodIPs_microblaze_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_microblaze_0_0/PmodIPs_microblaze_0_0_ooc_debug.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_microblaze_0_0/PmodIPs_microblaze_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_dlmb_v10_0/PmodIPs_dlmb_v10_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_ilmb_v10_0/PmodIPs_ilmb_v10_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_dlmb_bram_if_cntlr_0/PmodIPs_dlmb_bram_if_cntlr_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_ilmb_bram_if_cntlr_0/PmodIPs_ilmb_bram_if_cntlr_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_lmb_bram_0/PmodIPs_lmb_bram_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_xbar_0/PmodIPs_xbar_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_microblaze_0_axi_intc_0/PmodIPs_microblaze_0_axi_intc_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_microblaze_0_axi_intc_0/PmodIPs_microblaze_0_axi_intc_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_microblaze_0_axi_intc_0/PmodIPs_microblaze_0_axi_intc_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_mdm_1_0/PmodIPs_mdm_1_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_mdm_1_0/PmodIPs_mdm_1_0_ooc_trace.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_rst_clk_wiz_0_100M_0/PmodIPs_rst_clk_wiz_0_100M_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_rst_clk_wiz_0_100M_0/PmodIPs_rst_clk_wiz_0_100M_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_rst_clk_wiz_0_100M_0/PmodIPs_rst_clk_wiz_0_100M_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_1/bd_3da9_psr0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_1/bd_3da9_psr0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_2/bd_3da9_psr_aclk_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_2/bd_3da9_psr_aclk_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_3/bd_3da9_psr_aclk1_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_3/bd_3da9_psr_aclk1_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_4/bd_3da9_arsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_5/bd_3da9_rsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_6/bd_3da9_awsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_7/bd_3da9_wsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_8/bd_3da9_bsw_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_12/bd_3da9_s00a2s_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_13/bd_3da9_sarn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_13/bd_3da9_sarn_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_14/bd_3da9_srn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_14/bd_3da9_srn_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_15/bd_3da9_sawn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_15/bd_3da9_sawn_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_16/bd_3da9_swn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_16/bd_3da9_swn_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_17/bd_3da9_sbn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_17/bd_3da9_sbn_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_21/bd_3da9_s01a2s_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_22/bd_3da9_sarn_1_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_22/bd_3da9_sarn_1_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_23/bd_3da9_srn_1_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_23/bd_3da9_srn_1_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_24/bd_3da9_m00s2a_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_25/bd_3da9_m00arn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_25/bd_3da9_m00arn_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_26/bd_3da9_m00rn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_26/bd_3da9_m00rn_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_27/bd_3da9_m00awn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_27/bd_3da9_m00awn_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_28/bd_3da9_m00wn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_28/bd_3da9_m00wn_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_29/bd_3da9_m00bn_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/bd_0/ip/ip_29/bd_3da9_m00bn_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_smc_0/smartconnect.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_rst_mig_7series_0_81M_0/PmodIPs_rst_mig_7series_0_81M_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_rst_mig_7series_0_81M_0/PmodIPs_rst_mig_7series_0_81M_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_rst_mig_7series_0_81M_0/PmodIPs_rst_mig_7series_0_81M_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_3/PmodIPs_axi_gpio_0_3_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_3/PmodIPs_axi_gpio_0_3_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_3/PmodIPs_axi_gpio_0_3.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_6/PmodIPs_axi_gpio_0_6_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_6/PmodIPs_axi_gpio_0_6_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_6/PmodIPs_axi_gpio_0_6.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_uartlite_0_0/PmodIPs_axi_uartlite_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_uartlite_0_0/PmodIPs_axi_uartlite_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_uartlite_0_0/PmodIPs_axi_uartlite_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_mig_7series_0_0/PmodIPs_mig_7series_0_0/user_design/constraints/PmodIPs_mig_7series_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_mig_7series_0_0/PmodIPs_mig_7series_0_0/user_design/constraints/PmodIPs_mig_7series_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_mig_7series_0_0/PmodIPs_mig_7series_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_clk_wiz_0_0/PmodIPs_clk_wiz_0_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_clk_wiz_0_0/PmodIPs_clk_wiz_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_clk_wiz_0_0/PmodIPs_clk_wiz_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_8/PmodIPs_axi_gpio_0_8_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_8/PmodIPs_axi_gpio_0_8_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_axi_gpio_0_8/PmodIPs_axi_gpio_0_8.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/PmodIPs_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_microblaze_0_0/data/mb_bootloop_le.elf}}]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.srcs/constrs_1/imports/digilent-xdc-master/Arty-A7-100-Master.xdc}}
set_property used_in_implementation false [get_files {{D:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.srcs/constrs_1/imports/digilent-xdc-master/Arty-A7-100-Master.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental {D:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.srcs/utils_1/imports/synth_1/PmodIPs_wrapper.dcp}
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top PmodIPs_wrapper -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef PmodIPs_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file PmodIPs_wrapper_utilization_synth.rpt -pb PmodIPs_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
