#!/bin/bash -f
#**********************************************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Script generated by Vivado on Tue May 21 18:08:15 +1200 2024
# SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : design_1.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : design_1.sh
#                design_1.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                design_1.sh [-reset_run]
#                design_1.sh [-reset_log]
#                design_1.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'design_1.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +rwc -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xilinx_vip -libname xpm -libname xil_defaultlib -libname microblaze_v11_0_12 -libname lmb_v10_v3_0_13 -libname lmb_bram_if_cntlr_v4_0_23 -libname blk_mem_gen_v8_4_7 -libname generic_baseblocks_v2_1_1 -libname axi_infrastructure_v1_1_0 -libname axi_register_slice_v2_1_29 -libname fifo_generator_v13_2_9 -libname axi_data_fifo_v2_1_28 -libname axi_crossbar_v2_1_30 -libname axi_lite_ipif_v3_0_4 -libname axi_intc_v4_1_18 -libname xlconcat_v2_1_5 -libname mdm_v3_2_25 -libname lib_cdc_v1_0_2 -libname proc_sys_reset_v5_0_14 -libname xlconstant_v1_1_8 -libname smartconnect_v1_0 -libname axi_vip_v1_1_15 -libname lib_pkg_v1_0_3 -libname lib_srl_fifo_v1_0_3 -libname axi_uartlite_v2_0_33 -libname interrupt_control_v3_1_5 -libname axi_gpio_v2_0_31 -libname xilinx_vip -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xilinx_vip xpm xil_defaultlib microblaze_v11_0_12 lmb_v10_v3_0_13 lmb_bram_if_cntlr_v4_0_23 blk_mem_gen_v8_4_7 generic_baseblocks_v2_1_1 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_29 fifo_generator_v13_2_9 axi_data_fifo_v2_1_28 axi_crossbar_v2_1_30 axi_lite_ipif_v3_0_4 axi_intc_v4_1_18 xlconcat_v2_1_5 mdm_v3_2_25 lib_cdc_v1_0_2 proc_sys_reset_v5_0_14 xlconstant_v1_1_8 smartconnect_v1_0 axi_vip_v1_1_15 lib_pkg_v1_0_3 lib_srl_fifo_v1_0_3 axi_uartlite_v2_0_33 interrupt_control_v3_1_5 axi_gpio_v2_0_31)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2023.2 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xilinx_vip $xmvlog_opts -sv +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvlog -work xpm $xmvlog_opts -sv +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xpm $xmvhdl_opts \
  "C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_addr_decode.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_read.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_reg.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_reg_bank.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_top.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_write.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_ar_channel.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_aw_channel.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_b_channel.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_cmd_arbiter.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_cmd_fsm.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_cmd_translator.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_fifo.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_incr_cmd.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_r_channel.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_simple_fifo.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_wrap_cmd.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_wr_cmd_fsm.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_w_channel.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_axic_register_slice.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_axi_register_slice.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_axi_upsizer.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_a_upsizer.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_and.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_latch_and.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_latch_or.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_or.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_command_fifo.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_comparator.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_comparator_sel.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_comparator_sel_static.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_r_upsizer.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_w_upsizer.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_2_clk_ibuf.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_2_infrastructure.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_2_iodelay_ctrl.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_2_tempmon.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_arb_mux.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_arb_row_col.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_arb_select.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_cntrl.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_common.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_compare.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_mach.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_queue.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_state.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_col_mach.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_mc.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_rank_cntrl.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_rank_common.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_rank_mach.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_round_robin_arb.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_buf.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_dec_fix.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_gen.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_merge_enc.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_2_fi_xor.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v4_2_memc_ui_top_axi.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v4_2_mem_intfc.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_group_io.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_lane.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_calib_top.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_if_post_fifo.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy_wrapper.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_of_pre_fifo.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_4lanes.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ck_addr_cmd_delay.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal_hr.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_init.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_cntlr.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_data.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_edge.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_lim.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_mux.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_po_cntlr.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_samp.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_oclkdelay_cal.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_prbs_rdlvl.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_rdlvl.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_tempmon.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_top.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrcal.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl_off_delay.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_prbs_gen.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_skip_calib_tap.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_cc.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_edge_store.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_meta.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_pd.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_tap_base.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_top.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_2_ui_cmd.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_2_ui_rd_data.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_2_ui_top.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_2_ui_wr_data.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/design_1_mig_7series_0_0_mig_sim.v" \
  "../../../bd/design_1/ip/design_1_mig_7series_0_0_1/design_1_mig_7series_0_0/user_design/rtl/design_1_mig_7series_0_0.v" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_mmcm_pll_drp.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_0_0_conv_funs_pkg.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_0_0_proc_common_pkg.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_0_0_ipif_pkg.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_0_0_family_support.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_0_0_family.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_0_0_soft_reset.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/proc_common_v3_00_a/hdl/src/vhdl/design_1_clk_wiz_0_0_pselect_f.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/design_1_clk_wiz_0_0_address_decoder.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/design_1_clk_wiz_0_0_slave_attachment.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/design_1_clk_wiz_0_0_axi_lite_ipif.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz_drp.vhd" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_axi_clk_config.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work microblaze_v11_0_12 $xmvhdl_opts \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f557/hdl/microblaze_v11_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_microblaze_0_0/sim/design_1_microblaze_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lmb_v10_v3_0_13 $xmvhdl_opts \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ae24/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_dlmb_v10_1/sim/design_1_dlmb_v10_1.vhd" \
  "../../../bd/design_1/ip/design_1_ilmb_v10_1/sim/design_1_ilmb_v10_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lmb_bram_if_cntlr_v4_0_23 $xmvhdl_opts \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/1ca4/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_dlmb_bram_if_cntlr_1/sim/design_1_dlmb_bram_if_cntlr_1.vhd" \
  "../../../bd/design_1/ip/design_1_ilmb_bram_if_cntlr_1/sim/design_1_ilmb_bram_if_cntlr_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work blk_mem_gen_v8_4_7 $xmvlog_opts +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/3c0c/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_lmb_bram_1/sim/design_1_lmb_bram_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work generic_baseblocks_v2_1_1 $xmvlog_opts +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/10ab/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_29 $xmvlog_opts +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ff9f/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_9 $xmvlog_opts +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ac72/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work fifo_generator_v13_2_9 $xmvhdl_opts \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ac72/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_9 $xmvlog_opts +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ac72/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_data_fifo_v2_1_28 $xmvlog_opts +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/279e/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_crossbar_v2_1_30 $xmvlog_opts +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/fb47/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xbar_0/sim/design_1_xbar_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work axi_lite_ipif_v3_0_4 $xmvhdl_opts \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_intc_v4_1_18 $xmvhdl_opts \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/d764/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_microblaze_0_axi_intc_0/sim/design_1_microblaze_0_axi_intc_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xlconcat_v2_1_5 $xmvlog_opts +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/147b/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_microblaze_0_xlconcat_0/sim/design_1_microblaze_0_xlconcat_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work mdm_v3_2_25 $xmvhdl_opts \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/347d/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_mdm_1_1/sim/design_1_mdm_1_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_cdc_v1_0_2 $xmvhdl_opts \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_14 $xmvhdl_opts \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/408c/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_rst_clk_wiz_0_100M_1/sim/design_1_rst_clk_wiz_0_100M_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/sim/bd_6f02.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xlconstant_v1_1_8 $xmvlog_opts +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/d390/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_0/sim/bd_6f02_one_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_1/sim/bd_6f02_psr0_0.vhd" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_2/sim/bd_6f02_psr_aclk_0.vhd" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_3/sim/bd_6f02_psr_aclk1_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/bd53/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_4/sim/bd_6f02_arsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_5/sim/bd_6f02_rsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_6/sim/bd_6f02_awsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_7/sim/bd_6f02_wsw_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_8/sim/bd_6f02_bsw_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c6b2/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_9/sim/bd_6f02_s00mmu_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/abb8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_10/sim/bd_6f02_s00tr_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/7827/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_11/sim/bd_6f02_s00sic_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/79ce/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_12/sim/bd_6f02_s00a2s_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_13/sim/bd_6f02_sarn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_14/sim/bd_6f02_srn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_15/sim/bd_6f02_sawn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_16/sim/bd_6f02_swn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_17/sim/bd_6f02_sbn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_18/sim/bd_6f02_s01mmu_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_19/sim/bd_6f02_s01tr_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_20/sim/bd_6f02_s01sic_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_21/sim/bd_6f02_s01a2s_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_22/sim/bd_6f02_sarn_1.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_23/sim/bd_6f02_srn_1.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ebf7/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_24/sim/bd_6f02_m00s2a_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_25/sim/bd_6f02_m00arn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_26/sim/bd_6f02_m00rn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_27/sim/bd_6f02_m00awn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_28/sim/bd_6f02_m00wn_0.sv" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_29/sim/bd_6f02_m00bn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/6eea/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_30/sim/bd_6f02_m00e_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_vip_v1_1_15 $xmvlog_opts -sv +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/5753/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"C:/UNI/Y4S1/P4P/Vivado/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_smc_1/sim/design_1_axi_smc_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_rst_mig_7series_0_81M_1/sim/design_1_rst_mig_7series_0_81M_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_pkg_v1_0_3 $xmvhdl_opts \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/56d9/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_srl_fifo_v1_0_3 $xmvhdl_opts \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/02c4/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_uartlite_v2_0_33 $xmvhdl_opts \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/df48/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_uartlite_0_0/sim/design_1_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work interrupt_control_v3_1_5 $xmvhdl_opts \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/d8cc/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_gpio_v2_0_31 $xmvhdl_opts \
  "../../../../project_new_start_try_DC.gen/sources_1/bd/design_1/ipshared/6fbe/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_gpio_0_1/sim/design_1_axi_gpio_0_1.vhd" \
  "../../../bd/design_1/ip/design_1_axi_gpio_0_2/sim/design_1_axi_gpio_0_2.vhd" \
  "../../../bd/design_1/ip/design_1_axi_gpio_0_4/sim/design_1_axi_gpio_0_4.vhd" \
  "../../../bd/design_1/sim/design_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.design_1 xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.design_1 -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file


  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log design_1_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-step]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-reset_log]\n\
Usage: design_1.sh [-keep_index]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
