# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.srcs/sources_1/bd/PmodIPs/ip/PmodIPs_xbar_0/PmodIPs_xbar_0.xci
# IP: The module: 'PmodIPs_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_xbar_0/PmodIPs_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.srcs/sources_1/bd/PmodIPs/ip/PmodIPs_xbar_0/PmodIPs_xbar_0.xci
# IP: The module: 'PmodIPs_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Daniel/Documents/GitHub/p4p-2024-group57/Implementation Test/VivadoProjects/MyNewProject/MyNewProject.gen/sources_1/bd/PmodIPs/ip/PmodIPs_xbar_0/PmodIPs_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodIPs_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
